export const PROCUREMENT_PORTALS = [
  { group: "NATIONAL SLED + GOVERNMENT PROCUREMENT", sites: [
    { name: "GovTribe", url: "https://govtribe.com", focus: "Intelligence & Pursuit" },
    { name: "HigherGov", url: "https://highergov.com", focus: "Market Intel" },
    { name: "SAM.gov", url: "https://sam.gov", focus: "Prime Opportunities" },
    { name: "BidNet Direct", url: "https://bidnetdirect.com", focus: "National Local" },
    { name: "DemandStar", url: "https://demandstar.com", focus: "Government Purchasing" },
    { name: "GovWin IQ", url: "https://iq.govwin.com", focus: "Capture Management" },
    { name: "PennBid", url: "https://pennbid.procureware.com", focus: "PA Regional" },
    { name: "Bonfire", url: "https://gobonfire.com", focus: "Municipal/Schools" },
    { name: "OpenGov Procurement", url: "https://procurement.opengov.com", focus: "City/County" },
    { name: "IonWave", url: "https://ionwave.net", focus: "Education/SLED" },
    { name: "Public Purchase", url: "https://publicpurchase.com", focus: "Government Bids" },
    { name: "Beacon Bid", url: "https://beaconbid.com", focus: "Bid Distribution" },
    { name: "FindRFP", url: "https://findrfp.com", focus: "Solicitation Search" },
    { name: "RFPDB", url: "https://rfpdb.com", focus: "Database" },
    { name: "InstantMarkets", url: "https://instantmarkets.com", focus: "Aggregator" },
  ]},
  { group: "PENNSYLVANIA PROCUREMENT SITES", sites: [
    { name: "Pennsylvania eMarketplace", url: "http://www.emarketplace.state.pa.us", focus: "Statewide Bids" },
    { name: "COSTARS", url: "https://www.dgs.pa.gov/COSTARS", focus: "Cooperative Purchasing" },
    { name: "PennDOT ECMS", url: "https://www.ecms.penndot.pa.gov", focus: "Infrastructure" },
    { name: "PA Turnpike Procurement", url: "https://www.paturnpike.com/business/procurement", focus: "Turnpike Authority" },
    { name: "DCNR Procurement", url: "https://www.dcnr.pa.gov", focus: "Conservation/Natural Resources" },
    { name: "PA Treasury Procurement", url: "https://patreasury.gov", focus: "Financial/Treasury" },
  ]},
  { group: "PITTSBURGH / ALLEGHENY COUNTY PROCUREMENT", sites: [
    { name: "City of Pittsburgh Procurement", url: "https://pittsburghpa.gov/procurement", focus: "City Bids (Beacon)" },
    { name: "Allegheny County Procurement", url: "https://alleghenycounty.bonfirehub.com", focus: "County Bids (Bonfire)" },
    { name: "PWSA Procurement", url: "https://www.pgh2o.com/procurement", focus: "Water/Sewer" },
    { name: "Pittsburgh Regional Transit Procurement", url: "https://procurement.opengov.com/portal/rideprt", focus: "PRT/Transit" },
    { name: "URA Proposals", url: "https://www.ura.org/proposals", focus: "Redevelopment" },
    { name: "Sports & Exhibition Authority", url: "https://www.pgh-sea.com", focus: "Venue Management" },
    { name: "Airport Authority Procurement", url: "https://flypittsburgh.com/business", focus: "Aviation/Infra" },
    { name: "Pittsburgh Public Schools", url: "https://www.pghschools.org/procurement", focus: "Educational Bids" },
    { name: "CCAC Procurement", url: "https://www.ccac.edu/purchasing", focus: "Higher Education" },
    { name: "University of Pittsburgh Purchasing", url: "https://www.purchase.pitt.edu", focus: "Research/Education" },
  ]},
  { group: "REAL ESTATE / DEVELOPMENT / INFRASTRUCTURE", sites: [
    { name: "Urban Redevelopment Authority", url: "https://www.ura.org", focus: "City Development" },
    { name: "URA IonWave Portal", url: "https://ura.ionwave.net", focus: "URA Bids" },
    { name: "Pittsburgh Land Bank", url: "https://pghlandbank.org", focus: "Property Acquisition" },
    { name: "HUD", url: "https://hud.gov", focus: "Federal Housing" },
    { name: "Pennsylvania Housing Finance Agency", url: "https://phfa.org", focus: "Housing Finance" },
  ]},
  { group: "AI CONTRACT / GOVERNMENT AI PROCUREMENT", sites: [
    { name: "Starbridge AI", url: "https://starbridge.ai", focus: "AI Opportunities" },
    { name: "Civic IQ", url: "https://civiciq.com", focus: "Civic Technology" },
    { name: "Sourcewell Procurement Portal", url: "https://sourcewell-mn.gov", focus: "AI/Tech Coop" },
    { name: "GovTribe AI Searches", url: "https://govtribe.com", focus: "AI Intelligence" },
    { name: "HigherGov AI Searches", url: "https://highergov.com", focus: "AI Market Intel" },
  ]},
];

export const SUPPLIER_DIRECTORY = [
  { group: "GOVERNMENT IT / AI DISTRIBUTORS", suppliers: [
    { name: "Carahsoft", url: "https://carahsoft.com", terms: "Net 30-60", focus: "Primary Gov IT" },
    { name: "SHI", url: "https://shi.com", terms: "Net 30", focus: "Hardware/Software" },
    { name: "CDW Government", url: "https://cdwg.com", terms: "Net 30", focus: "IT Infrastructure" },
    { name: "Insight Public Sector", url: "https://insight.com", terms: "Net 30", focus: "Technology Solutions" },
  ]},
  { group: "AI PROVIDERS / CLOUD PARTNERS", suppliers: [
    { name: "Microsoft Azure AI", url: "https://azure.microsoft.com", focus: "Cloud/Gov AI" },
    { name: "AWS GovCloud", url: "https://aws.amazon.com/govcloud", focus: "Secure Cloud" },
    { name: "Google Public Sector", url: "https://cloud.google.com/public-sector", focus: "Gov Cloud/AI" },
    { name: "OpenAI", url: "https://openai.com", focus: "AI Models" },
    { name: "Anthropic", url: "https://anthropic.com", focus: "Safety-first AI" },
  ]},
  { group: "INDUSTRIAL / INFRASTRUCTURE SUPPLIERS", suppliers: [
    { name: "Grainger", url: "https://grainger.com", terms: "Net 30", focus: "MRO/Safety" },
    { name: "Fastenal", url: "https://fastenal.com", terms: "Net 30", focus: "Fasteners" },
    { name: "MSC Industrial Supply", url: "https://mscdirect.com", terms: "Net 30", focus: "Machining" },
    { name: "Global Industrial", url: "https://globalindustrial.com", terms: "Net 30", focus: "Equipment" },
    { name: "Wesco", url: "https://wesco.com", terms: "Net 30-60", focus: "Electrical/Data" },
    { name: "Graybar", url: "https://graybar.com", terms: "Net 30-60", focus: "Electrical/Comm" },
    { name: "Sonepar", url: "https://sonepar.com", terms: "Net 30-60", focus: "Electrical" },
  ]},
  { group: "WATER / SEWER / MUNICIPAL INFRASTRUCTURE SUPPLIERS", suppliers: [
    { name: "Core & Main", url: "https://coreandmain.com", terms: "Net 30-60", focus: "Utility Materials" },
    { name: "Ferguson", url: "https://ferguson.com", terms: "Net 30-60", focus: "Pipes/Valves" },
    { name: "Fortiline Waterworks", url: "https://fortiline.com", terms: "Net 30-60", focus: "Waterworks" },
    { name: "Pollardwater", url: "https://pollardwater.com", terms: "Net 30", focus: "Water Tools" },
  ]},
  { group: "FACILITY / JANITORIAL / OPERATIONS SUPPLIERS", suppliers: [
    { name: "HD Supply", url: "https://hdsupply.com", terms: "Net 30", focus: "Cleaning/Maint" },
    { name: "SupplyWorks", url: "https://supplyworks.com", terms: "Net 30", focus: "Janitorial" },
    { name: "Uline", url: "https://uline.com", terms: "Net 30", focus: "Shipping/Ops" },
    { name: "Quill", url: "https://quill.com", terms: "Net 30", focus: "Office Supplies" },
  ]},
  { group: "FLEET / TRANSPORTATION SUPPLIERS", suppliers: [
    { name: "FleetPride", url: "https://fleetpride.com", terms: "Net 30", focus: "Heavy-duty Parts" },
    { name: "NAPA Auto Parts", url: "https://napaonline.com", terms: "Net 30", focus: "Automotive" },
    { name: "Airgas", url: "https://airgas.com", terms: "Net 30-60", focus: "Specialty Gases" },
  ]},
  { group: "CONSTRUCTION / REAL ESTATE SUPPLIERS", suppliers: [
    { name: "ABC Supply", url: "https://abcsupply.com", terms: "Net 30", focus: "Roofing/Exterior" },
    { name: "84 Lumber", url: "https://84lumber.com", terms: "Net 30", focus: "Lumber/Building" },
    { name: "Builders FirstSource", url: "https://bldr.com", terms: "Net 30", focus: "Construction" },
    { name: "White Cap", url: "https://whitecap.com", terms: "Net 30", focus: "Industrial/Concrete" },
  ]},
];

export const OPPORTUNITIES = [
  { group: "Infrastructure / Public Works", items: [
    { title: "Traffic Signal Equipment", agency: "City of Pittsburgh", dueDate: "Active", portal: "Beacon", tags: ["Signal Heads", "Controllers", "Cabinets", "Poles", "Wiring"] },
    { title: "DOMI Trailer-Mounted Arrowboard RFQ", agency: "DOMI", dueDate: "Active", portal: "Beacon", tags: ["Traffic Management", "Arrow Boards", "Safety"] },
    { title: "DOMI Equipment Trailer RFQ", agency: "DOMI", dueDate: "Active", portal: "Beacon", tags: ["Utility Trailers", "Fleet"] },
    { title: "Compact Utility Vehicle Procurement", agency: "City of PGH", dueDate: "Active", portal: "Beacon", tags: ["Fleet", "Utility Vehicles"] },
    { title: "Backup Emergency Generator", agency: "Mellon Square Garage", dueDate: "Active", portal: "Beacon", tags: ["Electrical", "Infrastructure"] },
    { title: "Junction Box Frames Procurement", agency: "City of PGH", dueDate: "Active", portal: "Beacon", tags: ["Metal Fabrication", "Utility Castings"] },
  ]},
  { group: "WATER / SEWER / UTILITIES", items: [
    { title: "PWSA 2026 Sewer Reconstruction IDIQ", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["Infrastructure", "Sewer"] },
    { title: "PWSA Urgent Sewer CM/CI Services", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["CM/CI", "Professional"] },
    { title: "Lead Service Line QA/QC Services", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["QA/QC", "Lead"] },
    { title: "Lead Service Line CM/CI Services", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["CM/CI", "Lead"] },
    { title: "Catch Basin & Inlet Replacement", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["Replacement", "Sewer"] },
    { title: "Small Diameter Sewer Rehabilitation IDIQ", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["Rehab", "Sewer"] },
  ]},
  { group: "FLEET / TRANSPORTATION", items: [
    { title: "PWSA Fleet Purchase Opportunity", agency: "PWSA", dueDate: "Active", portal: "PWSA", tags: ["Fleet Procurement"] },
    { title: "Pittsburgh Regional Transit Fleet Maintenance", agency: "PRT", dueDate: "Active", portal: "OpenGov", tags: ["Supplies", "Maintenance"] },
    { title: "Police Drone Support Van Procurement", agency: "City of PGH", dueDate: "Active", portal: "Beacon", tags: ["Fleet", "Specialty Vehicle"] },
  ]},
  { group: "JANITORIAL / SUPPLY / CONSUMABLES", items: [
    { title: "PRT Janitorial Supplies", agency: "PRT", dueDate: "Active", portal: "OpenGov", tags: ["Facilities", "Cleaning"] },
    { title: "Allegheny Intermediate Unit Supply Bid", agency: "AIU", dueDate: "Active", portal: "AIU Portal", tags: ["Educational Supplies"] },
    { title: "Allegheny County Specialty Gases IFB", agency: "Allegheny County", dueDate: "Active", portal: "Bonfire", tags: ["Specialty Gases"] },
    { title: "Liquid Bituminous Material IFB", agency: "Allegheny County", dueDate: "Active", portal: "Bonfire", tags: ["Construction Materials"] },
  ]},
  { group: "EDUCATION OPPORTUNITIES", items: [
    { title: "PPS Surveillance Systems", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["Security", "IT"] },
    { title: "PPS Physician Services", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["Medical", "Services"] },
    { title: "PPS Behavioral Health Staffing", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["Health", "Staffing"] },
    { title: "PPS Solar Photovoltaic Systems", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["Energy", "Solar"] },
    { title: "PPS Audio Equipment", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["AV", "Education"] },
    { title: "PPS Furniture & Operational Supplies", agency: "PPS", dueDate: "Active", portal: "PPS Beacon", tags: ["Furniture", "Operations"] },
  ]},
  { group: "REAL ESTATE / REDEVELOPMENT", items: [
    { title: "OMI Building Redevelopment", agency: "URA", dueDate: "Active", portal: "URA RFP", tags: ["Strip District", "Mixed-use"] },
    { title: "Lower Hill Redevelopment Housing RFP", agency: "URA", dueDate: "Active", portal: "URA RFP", tags: ["Residential", "Lower Hill"] },
    { title: "Smithfield Street Reconstruction & Retail", agency: "City of PGH", dueDate: "Active", portal: "Beacon", tags: ["Activation", "Infrastructure"] },
    { title: "Brushton Station Transit-Oriented Development", agency: "PRT", dueDate: "Active", portal: "OpenGov", tags: ["ETOD", "Study"] },
  ]},
  { group: "NATIONAL AI CONTRACT OPPORTUNITIES", items: [
    { title: "Sourcewell Enterprise AI Platform RFP", agency: "Sourcewell", dueDate: "Active", portal: "Sourcewell", tags: ["Enterprise AI", "National"] },
    { title: "Michigan Government AI Chatbot", agency: "Michigan", dueDate: "Active", portal: "MI Portal", tags: ["AI Chatbot", "UX"] },
    { title: "Ed Tech JPA AI Platform Contract", agency: "Ed Tech JPA", dueDate: "Active", portal: "Ed Tech JPA", tags: ["Education AI", "SLED"] },
    { title: "Long Beach AI Consultant Opportunity", agency: "Long Beach", dueDate: "Active", portal: "DemandStar", tags: ["AI Strategy", "Consulting"] },
    { title: "Providence SD AI Training", agency: "Providence SD", dueDate: "Active", portal: "BidNet", tags: ["AI Education", "Training"] },
  ]},
  { group: "PENNSYLVANIA AI OPPORTUNITIES", items: [
    { title: "PASSHE Digital Credentialing Platform", agency: "PASSHE", dueDate: "Active", portal: "PASSHE", tags: ["AI", "Credentials"] },
    { title: "PASSHE Enterprise Data Environment", agency: "PASSHE", dueDate: "Active", portal: "PASSHE", tags: ["Data Env", "Support"] },
    { title: "PASSHE Third Iron Digital Services", agency: "PASSHE", dueDate: "Active", portal: "PASSHE", tags: ["Digital Services", "Extension"] },
    { title: "PA DOE Buy American Invoice Tracking", agency: "PA DOE", dueDate: "Active", portal: "eMarketplace", tags: ["OCR", "AI Tracking"] },
  ]},
  { group: "FEDERAL / HYBRID OPPORTUNITY", items: [
    { title: "USACE PEWARS Office Upgrades", agency: "US Army Corps of Engineers", dueDate: "Active", portal: "SAM.gov", tags: ["HVAC", "Electrical", "Flooring", "Reconstruction"] },
  ]},
];
