export const PROCUREMENT_PORTALS = [
  { group: "NATIONAL SLED + GOVERNMENT PROCUREMENT", sites: [
    { name: "GovTribe", url: "https://govtribe.com", focus: "Intelligence & Pursuit" },
    { name: "HigherGov", url: "https://highergov.com", focus: "Market Intel" },
    { name: "SAM.gov", url: "https://sam.gov", focus: "Prime Opportunities" },
    { name: "BidNet Direct", url: "https://bidnetdirect.com", focus: "National Local" },
    { name: "DemandStar", url: "https://demandstar.com", focus: "Government Purchasing" },
    { name: "GovWin IQ", url: "https://iq.govwin.com", focus: "Capture Management" },
    { name: "PennBid", url: "https://pennbid.procureware.com", focus: "PA Regional" },
    { name: "Bonfire", url: "https://gobonfire.com", focus: "Municipal/Schools" },
    { name: "OpenGov Procurement", url: "https://procurement.opengov.com", focus: "City/County" },
    { name: "IonWave", url: "https://ionwave.net", focus: "Education/SLED" },
    { name: "Public Purchase", url: "https://publicpurchase.com", focus: "Government Bids" },
    { name: "Beacon Bid", url: "https://beaconbid.com", focus: "Bid Distribution" },
    { name: "FindRFP", url: "https://findrfp.com", focus: "Solicitation Search" },
    { name: "RFPDB", url: "https://rfpdb.com", focus: "Database" },
    { name: "InstantMarkets", url: "https://instantmarkets.com", focus: "Aggregator" },
  ]},
  { group: "PENNSYLVANIA PROCUREMENT SITES", sites: [
    { name: "Pennsylvania eMarketplace", url: "http://www.emarketplace.state.pa.us", focus: "Statewide Bids" },
    { name: "COSTARS", url: "https://www.dgs.pa.gov/COSTARS", focus: "Cooperative Purchasing" },
    { name: "PennDOT ECMS", url: "https://www.ecms.penndot.pa.gov", focus: "Infrastructure" },
    { name: "PA Turnpike Procurement", url: "https://www.paturnpike.com/business/procurement", focus: "Turnpike Authority" },
    { name: "DCNR Procurement", url: "https://www.dcnr.pa.gov", focus: "Conservation/Natural Resources" },
    { name: "PA Treasury Procurement", url: "https://patreasury.gov", focus: "Financial/Treasury" },
  ]},
  { group: "PITTSBURGH / ALLEGHENY COUNTY PROCUREMENT", sites: [
    { name: "City of Pittsburgh Procurement", url: "https://pittsburghpa.gov/procurement", focus: "City Bids (Beacon)" },
    { name: "Allegheny County Procurement", url: "https://alleghenycounty.bonfirehub.com", focus: "County Bids (Bonfire)" },
    { name: "PWSA Procurement", url: "https://www.pgh2o.com/procurement", focus: "Water/Sewer" },
    { name: "Pittsburgh Regional Transit Procurement", url: "https://procurement.opengov.com/portal/rideprt", focus: "PRT/Transit" },
    { name: "URA Proposals", url: "https://www.ura.org/proposals", focus: "Redevelopment" },
    { name: "Sports & Exhibition Authority", url: "https://www.pgh-sea.com", focus: "Venue Management" },
    { name: "Airport Authority Procurement", url: "https://flypittsburgh.com/business", focus: "Aviation/Infra" },
    { name: "Pittsburgh Public Schools", url: "https://www.pghschools.org/procurement", focus: "Educational Bids" },
    { name: "CCAC Procurement", url: "https://www.ccac.edu/purchasing", focus: "Higher Education" },
    { name: "University of Pittsburgh Purchasing", url: "https://www.purchase.pitt.edu", focus: "Research/Education" },
  ]},
  { group: "REAL ESTATE / DEVELOPMENT / INFRASTRUCTURE", sites: [
    { name: "Urban Redevelopment Authority", url: "https://www.ura.org", focus: "City Development" },
    { name: "URA IonWave Portal", url: "https://ura.ionwave.net", focus: "URA Bids" },
    { name: "Pittsburgh Land Bank", url: "https://pghlandbank.org", focus: "Property Acquisition" },
    { name: "HUD", url: "https://hud.gov", focus: "Federal Housing" },
    { name: "Pennsylvania Housing Finance Agency", url: "https://phfa.org", focus: "Housing Finance" },
  ]},
  { group: "AI CONTRACT / GOVERNMENT AI PROCUREMENT", sites: [
    { name: "Starbridge AI", url: "https://starbridge.ai", focus: "AI Opportunities" },
    { name: "Civic IQ", url: "https://civiciq.com", focus: "Civic Technology" },
    { name: "Sourcewell Procurement Portal", url: "https://sourcewell-mn.gov", focus: "AI/Tech Coop" },
    { name: "GovTribe AI Searches", url: "https://govtribe.com", focus: "AI Intelligence" },
    { name: "HigherGov AI Searches", url: "https://highergov.com", focus: "AI Market Intel" },
  ]},
];

export const SUPPLIER_DIRECTORY = [
  { group: "GOVERNMENT IT / AI DISTRIBUTORS", suppliers: [
    { name: "Carahsoft", url: "https://carahsoft.com", terms: "Net 30-60", focus: "Primary Gov IT" },
    { name: "SHI", url: "https://shi.com", terms: "Net 30", focus: "Hardware/Software" },
    { name: "CDW Government", url: "https://cdwg.com", terms: "Net 30", focus: "IT Infrastructure" },
    { name: "Insight Public Sector", url: "https://insight.com", terms: "Net 30", focus: "Technology Solutions" },
  ]},
  { group: "AI PROVIDERS / CLOUD PARTNERS", suppliers: [
    { name: "Microsoft Azure AI", url: "https://azure.microsoft.com", focus: "Cloud/Gov AI" },
    { name: "AWS GovCloud", url: "https://aws.amazon.com/govcloud", focus: "Secure Cloud" },
    { name: "Google Public Sector", url: "https://cloud.google.com/public-sector", focus: "Gov Cloud/AI" },
    { name: "OpenAI", url: "https://openai.com", focus: "AI Models" },
    { name: "Anthropic", url: "https://anthropic.com", focus: "Safety-first AI" },
  ]},
  { group: "INDUSTRIAL / INFRASTRUCTURE SUPPLIERS", suppliers: [
    { name: "Grainger", url: "https://grainger.com", terms: "Net 30", focus: "MRO/Safety" },
    { name: "Fastenal", url: "https://fastenal.com", terms: "Net 30", focus: "Fasteners" },
    { name: "MSC Industrial Supply", url: "https://mscdirect.com", terms: "Net 30", focus: "Machining" },
    { name: "Global Industrial", url: "https://globalindustrial.com", terms: "Net 30", focus: "Equipment" },
    { name: "Wesco", url: "https://wesco.com", terms: "Net 30-60", focus: "Electrical/Data" },
    { name: "Graybar", url: "https://graybar.com", terms: "Net 30-60", focus: "Electrical/Comm" },
    { name: "Sonepar", url: "https://sonepar.com", terms: "Net 30-60", focus: "Electrical" },
  ]},
  { group: "WATER / SEWER / MUNICIPAL INFRASTRUCTURE SUPPLIERS", suppliers: [
    { name: "Core & Main", url: "https://coreandmain.com", terms: "Net 30-60", focus: "Utility Materials" },
    { name: "Ferguson", url: "https://ferguson.com", terms: "Net 30-60", focus: "Pipes/Valves" },
    { name: "Fortiline Waterworks", url: "https://fortiline.com", terms: "Net 30-60", focus: "Waterworks" },
    { name: "Pollardwater", url: "https://pollardwater.com", terms: "Net 30", focus: "Water Tools" },
  ]},
  { group: "FACILITY / JANITORIAL / OPERATIONS SUPPLIERS", suppliers: [
    { name: "HD Supply", url: "https://hdsupply.com", terms: "Net 30", focus: "Cleaning/Maint" },
    { name: "SupplyWorks", url: "https://supplyworks.com", terms: "Net 30", focus: "Janitorial" },
    { name: "Uline", url: "https://uline.com", terms: "Net 30", focus: "Shipping/Ops" },
    { name: "Quill", url: "https://quill.com", terms: "Net 30", focus: "Office Supplies" },
  ]},
  { group: "FLEET / TRANSPORTATION SUPPLIERS", suppliers: [
    { name: "FleetPride", url: "https://fleetpride.com", terms: "Net 30", focus: "Heavy-duty Parts" },
    { name: "NAPA Auto Parts", url: "https://napaonline.com", terms: "Net 30", focus: "Automotive" },
    { name: "Airgas", url: "https://airgas.com", terms: "Net 30-60", focus: "Specialty Gases" },
  ]},
  { group: "CONSTRUCTION / REAL ESTATE SUPPLIERS", suppliers: [
    { name: "ABC Supply", url: "https://abcsupply.com", terms: "Net 30", focus: "Roofing/Exterior" },
    { name: "84 Lumber", url: "https://84lumber.com", terms: "Net 30", focus: "Lumber/Building" },
    { name: "Builders FirstSource", url: "https://bldr.com", terms: "Net 30", focus: "Construction" },
    { name: "White Cap", url: "https://whitecap.com", terms: "Net 30", focus: "Industrial/Concrete" },
  ]},
];

export const OPPORTUNITIES = [
  // Goods & Supplies
  { title: "Traffic Signal Equipment", agency: "City of Pittsburgh", category: "Goods", dueDate: "Active", value: "TBD", portal: "Beacon", tags: ["Traffic", "Electrical"] },
  { title: "Arrow Board RFQ", agency: "DOMI", category: "Goods", dueDate: "Active", value: "RFQ", portal: "Beacon", tags: ["Fleet", "Safety"] },
  { title: "Equipment Trailer RFQ", agency: "DOMI", category: "Goods", dueDate: "Active", value: "RFQ", portal: "Beacon", tags: ["Fleet", "Logistics"] },
  { title: "Janitorial Supplies", agency: "PRT", category: "Goods", dueDate: "Active", value: "TBD", portal: "OpenGov", tags: ["Facilities"] },
  { title: "Specialty Gases (IFB)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "IFB", portal: "Bonfire", tags: ["Industrial"] },
  { title: "Water/Sewer Materials", agency: "PWSA", category: "Goods", dueDate: "Active", value: "TBD", portal: "PWSA", tags: ["Infrastructure"] },
  { title: "American Flags (IFB# 9422)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Annual", portal: "Bonfire", tags: ["General"] },
  { title: "Warehouse Lift Truck", agency: "PPS", category: "Goods", dueDate: "May 15, 2026", value: "$45k est", portal: "Beacon", tags: ["Equipment"] },
  { title: "Engine Replacement Parts", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Ongoing", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Cleaning Solvent Service", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Industrial"] },
  { title: "Oil and Fuel Analysis", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Gear Lubricant", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Supply", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Waste Oil Removal", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Environmental"] },
  { title: "Vision Care (#9410)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Managed", portal: "Bonfire", tags: ["Medical"] },

  // Real Estate & Development
  { title: "OMI Building Redevelopment", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Mixed-use", portal: "URA", tags: ["Development"] },
  { title: "Lower Hill Redevelopment", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Infrastructure", portal: "URA", tags: ["Security", "FF&E"] },
  { title: "Brushton Station ETOD", agency: "PRT", category: "Real Estate", dueDate: "Active", value: "Transit-oriented", portal: "OpenGov", tags: ["Development"] },
  { title: "Real Estate Appraisal Pool", agency: "HACP", category: "Real Estate", dueDate: "Rolling", value: "Multiple", portal: "HACP", tags: ["Appraisal"] },
  { title: "Pre-Demolition Asbestos Survey", agency: "City of PGH", category: "Real Estate", dueDate: "Rolling", value: "Survey", portal: "Beacon", tags: ["Environmental"] },
  { title: "Lower Hill Housing RFP", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Smart Building", portal: "URA", tags: ["Residential"] },
  { title: "Transit Retail Space", agency: "PRT", category: "Real Estate", dueDate: "Active", value: "Lease", portal: "OpenGov", tags: ["Leasing"] },

  // AI & Professional Services
  { title: "Enterprise AI Platform", agency: "Sourcewell", category: "AI / Tech", dueDate: "Active", value: "National", portal: "Sourcewell", tags: ["AI", "Automation"] },
  { title: "State Government AI Chatbot", agency: "Michigan", category: "AI / Tech", dueDate: "Active", value: "Statewide", portal: "MI Portal", tags: ["AI", "UX"] },
  { title: "AI Education Platforms", agency: "Ed Tech JPA", category: "AI / Tech", dueDate: "Active", value: "Multiple", portal: "Ed Tech JPA", tags: ["EdTech", "AI"] },
  { title: "AI Consultant Opportunity", agency: "Various", category: "AI / Tech", dueDate: "Active", value: "Strategy", portal: "DemandStar", tags: ["Consulting"] },
  { title: "District AI Training", agency: "Providence SD", category: "AI / Tech", dueDate: "Active", value: "Training", portal: "BidNet", tags: ["Training"] },
  { title: "Digital Credentialing", agency: "PASSHE", category: "AI / Tech", dueDate: "Active", value: "Analytics", portal: "PASSHE", tags: ["AI", "Data"] },
  { title: "Enterprise Data Env", agency: "PASSHE", category: "AI / Tech", dueDate: "Active", value: "BI", portal: "PASSHE", tags: ["Data", "IT"] },
  { title: "Invoice Automation", agency: "PA DOE", category: "AI / Tech", dueDate: "Active", value: "OCR", portal: "eMarketplace", tags: ["AI", "Finance"] },
  { title: "Workforce Analysis (RFP 26-23)", agency: "PRT", category: "AI / Tech", dueDate: "Active", value: "Consulting", portal: "OpenGov", tags: ["Analytics"] },
  { title: "Structured Data Cabling", agency: "City of PGH", category: "AI / Tech", dueDate: "Active", value: "Infrastructure", portal: "Beacon", tags: ["IT Infra"] },
  { title: "Marketing/Utility Consulting", agency: "PRT", category: "AI / Tech", dueDate: "Active", value: "Service", portal: "OpenGov", tags: ["Consulting"] },

  // Infrastructure & Construction
  { title: "Boiler Upgrades (#202601)", agency: "PPS", category: "Infrastructure", dueDate: "May 18, 2026", value: "HVAC", portal: "Beacon Bid", tags: ["Renovation"] },
  { title: "Playground Renovations", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Public Works", portal: "Bonfire", tags: ["Park"] },
  { title: "ACJ Detention Center Reno", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Construction", portal: "Bonfire", tags: ["Security"] },
  { title: "Roof Replacement", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "South Park", portal: "Bonfire", tags: ["Roofing"] },
  { title: "Biology Lab Renovations", agency: "CCAC", category: "Infrastructure", dueDate: "Active", value: "CCAC", portal: "Bonfire", tags: ["Renovation"] },
  { title: "Smithfield St Reconstruction", agency: "City of PGH", category: "Infrastructure", dueDate: "Active", value: "Streetscape", portal: "Beacon", tags: ["Roadwork"] },
  { title: "Detention Center HVAC", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "HVAC", portal: "Bonfire", tags: ["HVAC"] },
  { title: "Traffic Control Rental", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Rental", portal: "Bonfire", tags: ["Roadwork"] },
];
