export const PORTALS = [
  { name: "Allegheny County Bonfire", url: "https://alleghenycounty.bonfirehub.com/portal/?tab=openOpportunities", category: "Local Government", focus: "County Level Bids" },
  { name: "City of Pittsburgh Beacon", url: "https://pittsburghpa.gov/beacon/opportunities.html", category: "City Level", focus: "Beacon Bids" },
  { name: "PRT Procurement (OpenGov)", url: "https://procurement.opengov.com/portal/rideprt", category: "Regional Transit", focus: "Transit/Fleet Bids" },
  { name: "PPS Beacon Bid", url: "https://www.pghschools.org/Page/5453", category: "School District", focus: "Educational Supplies" },
  { name: "URA Proposals & Bids", url: "https://www.ura.org/pages/proposals-bids", category: "Redevelopment", focus: "Real Estate/Infra" },
  { name: "PWSA Procurement", url: "https://www.pgh2o.com/about-us/procurement/current-opportunities", category: "Water / Sewer", focus: "Utility Materials" },
  { name: "PA eMarketplace", url: "http://www.emarketplace.state.pa.us/Search.aspx", category: "State Level", focus: "Statewide Contracts" },
  { name: "PennDOT ECMS", url: "https://www.ecms.penndot.pa.gov/", category: "Construction", focus: "Infrastructure" },
  { name: "CCAC Procurement", url: "https://www.ccac.edu/business/purchasing/index.php", category: "Higher Ed", focus: "College Supplies" },
  { name: "BidNet Direct (PA Group)", url: "https://www.bidnetdirect.com/pennsylvania", category: "Aggregator", focus: "Regional Aggregate" },
  { name: "GovTribe (SLED)", url: "https://govtribe.com/", category: "Aggregator", focus: "Market Intelligence" },
  { name: "Starbridge AI", url: "https://starbridge.ai/", category: "AI Specific", focus: "AI Opportunities" },
  { name: "HigherGov", url: "https://highergov.com", category: "Federal/SLED", focus: "Market Intel" },
  { name: "SAM.gov", url: "https://sam.gov", category: "Federal", focus: "Prime Opportunities" },
];

export const SUPPLIERS = [
  { name: "Grainger", category: "Industrial / MRO", terms: "Net 30", focus: "Tools, Safety", status: "Action Required" },
  { name: "Fastenal", category: "Industrial / MRO", terms: "Net 30", focus: "Fasteners, Tools", status: "Action Required" },
  { name: "MSC Industrial", category: "Industrial / MRO", terms: "Net 30", focus: "Machining", status: "Action Required" },
  { name: "HD Supply", category: "Janitorial / Facility", terms: "Net 30", focus: "Cleaning", status: "Action Required" },
  { name: "Uline", category: "Janitorial / Facility", terms: "Net 30", focus: "Shipping", status: "Action Required" },
  { name: "Quill", category: "Janitorial / Facility", terms: "Net 30", focus: "Office", status: "Action Required" },
  { name: "Wesco", category: "Electrical", terms: "Net 30-60", focus: "Lighting, Infra", status: "Action Required" },
  { name: "Graybar", category: "Electrical", terms: "Net 30-60", focus: "Networking", status: "Action Required" },
  { name: "Ferguson", category: "Water / Sewer", terms: "Net 30-60", focus: "Pipes, Valves", status: "Action Required" },
  { name: "Core & Main", category: "Water / Sewer", terms: "Net 30-60", focus: "Utility", status: "Action Required" },
  { name: "NAPA Auto Parts", category: "Fleet / Parts", terms: "Net 30", focus: "Vehicles", status: "Action Required" },
  { name: "FleetPride", category: "Fleet / Parts", terms: "Net 30", focus: "Heavy-duty", status: "Action Required" },
  { name: "Airgas", category: "Fleet / Parts", terms: "Net 30-60", focus: "Specialty Gases", status: "Action Required" },
  { name: "Amazon Business", category: "IT / Electronics", terms: "Net 30", focus: "General Tech", status: "Action Required" },
  { name: "CDW-G", category: "IT / Electronics", terms: "Net 30", focus: "Hardware", status: "Action Required" },
];

export const OPPORTUNITIES = [
  // Goods & Supplies
  { title: "Traffic Signal Equipment", agency: "City of Pittsburgh", category: "Goods", dueDate: "Active", value: "TBD", portal: "Beacon", tags: ["Traffic", "Electrical"] },
  { title: "Arrow Board RFQ", agency: "DOMI", category: "Goods", dueDate: "Active", value: "RFQ", portal: "Beacon", tags: ["Fleet", "Safety"] },
  { title: "Equipment Trailer RFQ", agency: "DOMI", category: "Goods", dueDate: "Active", value: "RFQ", portal: "Beacon", tags: ["Fleet", "Logistics"] },
  { title: "Janitorial Supplies", agency: "PRT", category: "Goods", dueDate: "Active", value: "TBD", portal: "OpenGov", tags: ["Facilities"] },
  { title: "Specialty Gases (IFB)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "IFB", portal: "Bonfire", tags: ["Industrial"] },
  { title: "Water/Sewer Materials", agency: "PWSA", category: "Goods", dueDate: "Active", value: "TBD", portal: "PWSA", tags: ["Infrastructure"] },
  { title: "American Flags (IFB# 9422)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Annual", portal: "Bonfire", tags: ["General"] },
  { title: "Warehouse Lift Truck", agency: "PPS", category: "Goods", dueDate: "May 15, 2026", value: "$45k est", portal: "Beacon", tags: ["Equipment"] },
  { title: "Engine Replacement Parts", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Ongoing", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Cleaning Solvent Service", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Industrial"] },
  { title: "Oil and Fuel Analysis", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Gear Lubricant", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Supply", portal: "Bonfire", tags: ["Fleet"] },
  { title: "Waste Oil Removal", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Service", portal: "Bonfire", tags: ["Environmental"] },
  { title: "Vision Care (#9410)", agency: "Allegheny County", category: "Goods", dueDate: "Active", value: "Managed", portal: "Bonfire", tags: ["Medical"] },

  // Real Estate & Development
  { title: "OMI Building Redevelopment", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Mixed-use", portal: "URA", tags: ["Development"] },
  { title: "Lower Hill Redevelopment", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Infrastructure", portal: "URA", tags: ["Security", "FF&E"] },
  { title: "Brushton Station ETOD", agency: "PRT", category: "Real Estate", dueDate: "Active", value: "Transit-oriented", portal: "OpenGov", tags: ["Development"] },
  { title: "Real Estate Appraisal Pool", agency: "HACP", category: "Real Estate", dueDate: "Rolling", value: "Multiple", portal: "HACP", tags: ["Appraisal"] },
  { title: "Pre-Demolition Asbestos Survey", agency: "City of PGH", category: "Real Estate", dueDate: "Rolling", value: "Survey", portal: "Beacon", tags: ["Environmental"] },
  { title: "Lower Hill Housing RFP", agency: "URA", category: "Real Estate", dueDate: "Active", value: "Smart Building", portal: "URA", tags: ["Residential"] },
  { title: "Transit Retail Space", agency: "PRT", category: "Real Estate", dueDate: "Active", value: "Lease", portal: "OpenGov", tags: ["Leasing"] },

  // AI & Professional Services
  { title: "Enterprise AI Platform", agency: "Sourcewell", category: "AI / Tech", dueDate: "Active", value: "National", portal: "Sourcewell", tags: ["AI", "Automation"] },
  { title: "State Government AI Chatbot", agency: "Michigan", category: "AI / Tech", dueDate: "Active", value: "Statewide", portal: "MI Portal", tags: ["AI", "UX"] },
  { title: "AI Education Platforms", agency: "Ed Tech JPA", category: "AI / Tech", dueDate: "Active", value: "Multiple", portal: "Ed Tech JPA", tags: ["EdTech", "AI"] },
  { title: "AI Consultant Opportunity", agency: "Various", category: "AI / Tech", dueDate: "Active", value: "Strategy", portal: "DemandStar", tags: ["Consulting"] },
  { title: "District AI Training", agency: "Providence SD", category: "AI / Tech", dueDate: "Active", value: "Training", portal: "BidNet", tags: ["Training"] },
  { title: "Digital Credentialing", agency: "PASSHE", category: "AI / Tech", dueDate: "Active", value: "Analytics", portal: "PASSHE", tags: ["AI", "Data"] },
  { title: "Enterprise Data Env", agency: "PASSHE", category: "AI / Tech", dueDate: "Active", value: "BI", portal: "PASSHE", tags: ["Data", "IT"] },
  { title: "Invoice Automation", agency: "PA DOE", category: "AI / Tech", dueDate: "Active", value: "OCR", portal: "eMarketplace", tags: ["AI", "Finance"] },
  { title: "Workforce Analysis (RFP 26-23)", agency: "PRT", category: "AI / Tech", dueDate: "Active", value: "Consulting", portal: "OpenGov", tags: ["Analytics"] },
  { title: "Structured Data Cabling", agency: "City of PGH", category: "AI / Tech", dueDate: "Active", value: "Infrastructure", portal: "Beacon", tags: ["IT Infra"] },
  { title: "Marketing/Utility Consulting", agency: "PRT", category: "AI / Tech", dueDate: "Active", value: "Service", portal: "OpenGov", tags: ["Consulting"] },

  // Infrastructure & Construction
  { title: "Boiler Upgrades (#202601)", agency: "PPS", category: "Infrastructure", dueDate: "May 18, 2026", value: "HVAC", portal: "Beacon Bid", tags: ["Renovation"] },
  { title: "Playground Renovations", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Public Works", portal: "Bonfire", tags: ["Park"] },
  { title: "ACJ Detention Center Reno", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Construction", portal: "Bonfire", tags: ["Security"] },
  { title: "Roof Replacement", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "South Park", portal: "Bonfire", tags: ["Roofing"] },
  { title: "Biology Lab Renovations", agency: "CCAC", category: "Infrastructure", dueDate: "Active", value: "CCAC", portal: "Bonfire", tags: ["Renovation"] },
  { title: "Smithfield St Reconstruction", agency: "City of PGH", category: "Infrastructure", dueDate: "Active", value: "Streetscape", portal: "Beacon", tags: ["Roadwork"] },
  { title: "Detention Center HVAC", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "HVAC", portal: "Bonfire", tags: ["HVAC"] },
  { title: "Traffic Control Rental", agency: "Allegheny County", category: "Infrastructure", dueDate: "Active", value: "Rental", portal: "Bonfire", tags: ["Roadwork"] },
];
